# Dataframe for analysis was generated by script from Securities info entry.R 

# Function
asset_builder2 <- function(x){
  
  # Create variable to contain variables of all assets
  result_df <- NULL
  
  # Create variable to contain data of single asset
  result_ts <- NULL
  
  # For each asset
  for (m in 1:length(x[[1]])){
  
    # For each period
    for (n in 1:length(df_nested_list[[2]][[1]])){
      
      # Extend time series
      Date_extension <- seq.Date(from = as.Date(x[[2]][[m]][[n]]),
                                 to = as.Date(x[[3]][[m]][[n]]),
                                 by = "day")
      
      # Add number of assets for the following period
      ts_period <- data.frame(Date_extension, x[[4]][[m]][[n]])
      
      # Give column names to data set
      colnames(ts_period) <- c("Date", "Number")
      
      # Glue time seried
      result_ts <- rbind(result_ts, ts_period)
    }
    
    # Get data 
    asset_prices <- getSymbols(x[[1]][[m]],
                               from = x[[2]][[m]][[1]],
                               to = x[[3]][[m]][[length(x[[2]][[m]])]],
                               src = "yahoo",
                               auto.assign=FALSE)[,4]
    
    # Get rid of NAs
    asset_prices <- asset_prices[apply(asset_prices,1,
                                       function(x) all(!is.na(x))),]
    # Put the tickers in data set
    colnames(asset_prices) <- x[[1]][[m]]
    
    # Make data discrete
    asset_Returns <- ROC(asset_prices, type = "discrete")
    
    # Make it time series
    asset_Returns <-as.timeSeries(asset_prices)
    
    # Subset dates from data set
    dates_fr_yh <- rownames(asset_Returns)
    
    # Transform them into a date format
    dates_fr_yh <- as.Date(dates_fr_yh)
    
    # Merge asset values with its dates
    ds_from_yahoo <- data.frame(dates_fr_yh, asset_Returns)
    
    # Change column name to Date
    colnames(ds_from_yahoo)[colnames(ds_from_yahoo) == 'dates_fr_yh'] <- 'Date'
    
    # Create index numbers for data set
    index_for_fl <- index(ds_from_yahoo)
    
    # Join index as row names
    rownames(ds_from_yahoo) <- index_for_fl
    
    # merge actual ownership period with
    final_m_t <- merge(x = ds_from_yahoo,
                              y = result_ts,
                              by = c("Date"))
    
    # Create variable with total sum of asset
    final_m_t$total_sum <- final_m_t[,2] * final_m_t$Number
    
    # If it is first column
    if (is.null(result_df)){ 
      
      # Equal it to 
      result_df = final_m_t  
    } else {
      
      # Or merge it with previously processed column
      result_df <- merge(x = result_df,
            y = final_m_t,
            by = "Date",
            all = TRUE)          
        }
  }
  
  # Substitute NAs with Zero values
  result_df[is.na(result_df)] <- 0
  
  # Display values
  return(result_df)
}
# Test
asset_builder2(df_nested_list)
