# Dataframe for analysis was generated by script from Securities info entry.R 

# Function
asset_builder2 <- function(x){ result_df <- NULL # Variable to contain values

  for (m in seq(x[,1])){ # For each asset
    
    v.t <- x[[1]][[m]] # Ticker
    
    s <- x[[2]][[m]] # Start date
    
    e <- x[[3]][[m]] # End date
    
    q <- x[[4]][[m]] # Asset number
    
    l <- length(s) # Length of Dates and Numbers
    
    result_ts <- NULL # Create variable to contain data of single asset
    
    for (n in seq(l)){ # Extend time series and add asset number
      
      result_ts<-rbind(result_ts,data.frame(Date=seq.Date(from=as.Date(s[[n]]),
                                                          to = as.Date(e[[n]]),
                                                          by = "day"),
                                            Number = q[[n]]))}
    # Get data 
    prices<-getSymbols(v.t,from=s[[1]],to=e[[l]],src="yahoo",auto.assign=F)[,4]
    
    prices <- prices[apply(prices, 1, function(x) all(!is.na(x))),] # NA off
    
    colnames(prices) <- v.t # Put the tickers in data set
    
    # Subset dates from data set and transform them into a date format
    dates_fr_yh <- as.Date(rownames(as.timeSeries(prices)))
    
    # Merge asset values with its dates
    ds_from_yahoo <- data.frame(dates_fr_yh, as.timeSeries(prices))
    
    # Change column name to Date
    colnames(ds_from_yahoo)[colnames(ds_from_yahoo) == 'dates_fr_yh'] <- 'Date'
    
    # Create index numbers for data set and join as row names
    rownames(ds_from_yahoo) <- seq(nrow(ds_from_yahoo))
    
    # merge actual ownership period with
    f.df <- merge(x = ds_from_yahoo, y = result_ts, by = c("Date"))
    
    f.df$total_sum <- f.df[,2] * f.df$Number # Total sum of asset
    
    # Add Ticker to Number
    colnames(f.df)[colnames(f.df) == 'Number'] <- sprintf("%s Number", v.t)
    
    # Add Ticker to Total
    colnames(f.df)[colnames(f.df) == 'total_sum'] <- sprintf("%s Total", v.t)
    
    # If it is first column, define it to new name
    if (is.null(result_df)){ result_df = f.df } else {
      
      # Or merge it with previously processed column
      result_df <- merge(x = result_df, y = f.df, by = "Date", all = T) } }
  
  result_df[is.na(result_df)] <- 0 # Substitute NA with Zero values
  
  rownames(result_df) <- result_df$Date # Put Dates in index
  
  result_df <- result_df[,-1] # Subset Time Series from data set 
  
  # Total amount of investments
  result_df$Total <- rowSums(result_df[,c(seq(ncol(result_df)/3)*3)], na.rm=T)
  
  result_df <- as.timeSeries(result_df) # Make it time series
  
  return(result_df) # Display values
}
# Test
asset_builder2(df_nested_list)
